/* CHARTS.JS - SVG renderer for finalized Laiban training results.
   Curves are read from TRAINED_POLICY.training_curves generated by
   training/train_q_learning.py after the 2000-episode run. */

function svgLine(series,opts){
  var W=680,H=opts.h||210,P={l:44,r:12,t:12,b:26};
  var xs=series[0].d.length;
  var lo=opts.min!==undefined?opts.min:Math.min.apply(null,series.map(function(s){return Math.min.apply(null,s.d)}));
  var hi=opts.max!==undefined?opts.max:Math.max.apply(null,series.map(function(s){return Math.max.apply(null,s.d)}));
  var pad=(hi-lo)*0.08||1;lo-=pad;hi+=pad;
  function X(i){return P.l+(W-P.l-P.r)*i/(xs-1)}
  function Y(v){return P.t+(H-P.t-P.b)*(1-(v-lo)/(hi-lo))}
  var s='<svg class="chart" viewBox="0 0 '+W+' '+H+'" preserveAspectRatio="none">';
  for(var g=0;g<=4;g++){var y=P.t+(H-P.t-P.b)*g/4,val=hi-(hi-lo)*g/4;
    s+='<line x1="'+P.l+'" y1="'+y+'" x2="'+(W-P.r)+'" y2="'+y+'" stroke="var(--chart-grid)" stroke-width="1"/>';
    s+='<text x="'+(P.l-7)+'" y="'+(y+3.5)+'" fill="var(--chart-label)" font-size="9.5" text-anchor="end">'+val.toFixed(opts.dp||2)+'</text>';}
  [0,0.25,0.5,0.75,1].forEach(function(f){var i=Math.round(f*(xs-1));
    s+='<text x="'+X(i)+'" y="'+(H-8)+'" fill="var(--chart-label)" font-size="9.5" text-anchor="middle">'+(opts.xs?opts.xs[i]:i)+'</text>';});
  series.forEach(function(se){
    var p="";se.d.forEach(function(v,i){p+=(i?" L":"M")+X(i).toFixed(1)+" "+Y(v).toFixed(1)});
    s+='<path d="'+p+'" fill="none" stroke="'+se.c+'" stroke-width="'+(se.w||2.2)+'" stroke-linejoin="round"'+(se.dash?' stroke-dasharray="5 5"':'')+'/>';
  });
  s+='<text x="'+(W/2)+'" y="'+(H-8)+'" fill="var(--chart-label)" font-size="9.5" text-anchor="middle" opacity="0">.</text>';
  s+='</svg>';
  return s;
}

/* ============================================================================
   STEP 8 — training curves generated by the finalized Laiban Step 7 experiment.
   No illustrative or hand-authored convergence values are used here.
   ============================================================================ */

var SIM=(function(){

  if(
    typeof TRAINED_POLICY==="undefined" ||
    !TRAINED_POLICY.training_curves
  ){
    return {
      ep:[],
      mq:[],
      sq:[],
      sp:[]
    };
  }

  var c=TRAINED_POLICY.training_curves;

  return {
    ep:c.episode || [],
    mq:c.modql_reward || [],
    sq:c.standard_reward || [],
    sp:c.q1_q2_spread || []
  };

})();