"""
make_sim_js.py
=============================================================================
Converts training_log.csv (the real training log from train_q_learning.py)
into a drop-in replacement for the hand-authored `SIM` object at the top of
charts.js -- same field names (ep, mq, sq, fj, fs, sp, dr), same shape
(60 evenly-spaced points), so nothing else in charts.js or analysis.js
needs to change.

Field mapping (matches how SIM is actually used in analysis.js):
    ep -> episode number
    mq -> MODQL composite reward per episode      (was: reward_modql)
    sq -> Standard Q-learning reward per episode   (was: reward_standard)
    fj -> MODQL fairness (Jain's Index)            (was: fairness_modql)
    fs -> Standard fairness (Jain's Index)         (was: fairness_standard)
    sp -> mean |Q1 - Q2| spread, MODQL              (was: q_drift_modql)
    dr -> single-table update drift, Standard       (was: q_drift_standard)

Run:
    python3 make_sim_js.py
Reads:  ./outputs/training_log.csv
Writes: ./outputs/sim_block.js   <- paste this over the `var SIM = ...` block
"""

import os
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
IN_CSV = os.path.join(HERE, "outputs", "training_log.csv")
OUT_JS = os.path.join(HERE, "outputs", "sim_block.js")

N_POINTS = 60          # same point count as the original hand-authored SIM
SMOOTH_WINDOW = 15      # light moving-average smoothing before downsampling


def downsample(series, n_points, window):
    smoothed = series.rolling(window, min_periods=1).mean()
    idx = [round(i * (len(smoothed) - 1) / (n_points - 1)) for i in range(n_points)]
    return smoothed.iloc[idx].round(4).tolist()


def js_array(values):
    return "[" + ",".join(f"{v:g}" for v in values) + "]"


def main():
    df = pd.read_csv(IN_CSV)

    ep = downsample(df["episode"], N_POINTS, 1)
    ep = [int(round(v)) for v in ep]  # episode numbers should be whole
    mq = downsample(df["reward_modql"], N_POINTS, SMOOTH_WINDOW)
    sq = downsample(df["reward_standard"], N_POINTS, SMOOTH_WINDOW)
    fj = downsample(df["fairness_modql"], N_POINTS, SMOOTH_WINDOW)
    fs = downsample(df["fairness_standard"], N_POINTS, SMOOTH_WINDOW)
    sp = downsample(df["q_drift_modql"], N_POINTS, SMOOTH_WINDOW)
    dr = downsample(df["q_drift_standard"], N_POINTS, SMOOTH_WINDOW)

    js = (
        "/* REAL training log from train_q_learning.py -- "
        f"{len(df)} episodes, downsampled to {N_POINTS} points for the chart.\n"
        "   Generated by make_sim_js.py. This replaces the old hand-authored\n"
        "   illustrative SIM block -- keep the variable name `SIM` and the\n"
        "   field names (ep/mq/sq/fj/fs/sp/dr) so nothing else in charts.js\n"
        "   or analysis.js needs to change. */\n"
        "var SIM = {\n"
        f"  ep:{js_array(ep)},\n"
        f"  mq:{js_array(mq)},\n"
        f"  sq:{js_array(sq)},\n"
        f"  fj:{js_array(fj)},\n"
        f"  fs:{js_array(fs)},\n"
        f"  sp:{js_array(sp)},\n"
        f"  dr:{js_array(dr)}\n"
        "};\n"
    )

    with open(OUT_JS, "w") as f:
        f.write(js)
    print(f"Wrote {OUT_JS}")
    print(f"({len(df)} episodes -> {N_POINTS} points)")


if __name__ == "__main__":
    main()
