/* ============================================================================
   MAZE DEMO / CONTROLLED ALGORITHM COMPARISON
   Standard Q-Learning (control) vs MODQL (proposed)

   Thesis-aligned micro-routing sandbox. Both agents receive the SAME 10x10
   obstacle layout and community demand/history. This demonstrates mechanics;
   it is NOT final Chapter 4 performance evidence.
   ============================================================================ */
(function(){
'use strict';
var SIZE=10,MAX_STEPS=100,TICK=650,MOVES=[[-1,0],[1,0],[0,-1],[0,1]];
var HUB={id:'hub',r:0,c:0,demand:0,visits:0};
var COMM=[{id:'A',r:1,c:8,demand:42,visits:2},{id:'B',r:4,c:5,demand:71,visits:0},{id:'C',r:8,c:2,demand:36,visits:1},{id:'D',r:8,c:8,demand:58,visits:3}];
var ALL=[HUB].concat(COMM),BY={};ALL.forEach(function(n){BY[n.id]=n;});
function key(r,c){return r+','+c;}function rng(seed){var s=seed>>>0;return function(){s=(s*1664525+1013904223)>>>0;return s/4294967296;};}
function jain(v){var s=0,q=0;v.forEach(function(x){s+=x;q+=x*x;});return q===0?1:(s*s)/(v.length*q);}function bucket(v,c){for(var i=0;i<c.length;i++)if(v<c[i])return i;return c.length;}
function bfs(g,a,b){var q=[[a,[a]]],seen={};seen[key(a[0],a[1])]=1;while(q.length){var z=q.shift(),p=z[0],path=z[1];if(p[0]===b[0]&&p[1]===b[1])return path;for(var i=0;i<4;i++){var r=p[0]+MOVES[i][0],c=p[1]+MOVES[i][1],k=key(r,c);if(r<0||c<0||r>=SIZE||c>=SIZE||g[r][c]||seen[k])continue;seen[k]=1;q.push([[r,c],path.concat([[r,c]])]);}}return[];}
function makeMaze(seed){var R=rng(seed),g=Array.from({length:SIZE},function(){return Array(SIZE).fill(0);}),fixed={};ALL.forEach(function(n){fixed[key(n.r,n.c)]=1;});var n=0;while(n<18){var r=Math.floor(R()*SIZE),c=Math.floor(R()*SIZE);if(fixed[key(r,c)]||g[r][c])continue;g[r][c]=1;n++;}COMM.forEach(function(x){var guard=0;while(!bfs(g,[0,0],[x.r,x.c]).length&&guard++<80){var obs=[];for(var r=0;r<SIZE;r++)for(var c=0;c<SIZE;c++)if(g[r][c])obs.push([r,c]);var p=obs[Math.floor(R()*obs.length)];g[p[0]][p[1]]=0;}});return g;}
function World(seed){this.seed=seed;this.grid=makeMaze(seed);}World.prototype.route=function(a,b){return bfs(this.grid,[BY[a].r,BY[a].c],[BY[b].r,BY[b].c]);};World.prototype.access=function(id){var n=BY[id],open=0,total=0;for(var i=0;i<4;i++){var r=n.r+MOVES[i][0],c=n.c+MOVES[i][1];if(r<0||c<0||r>=SIZE||c>=SIZE)continue;total++;if(!this.grid[r][c])open++;}return total?open/total:0;};
function Standard(){this.Q={};this.a=.1;this.g=.9;this.e=.2;}Standard.prototype.state=function(s){return s.current;};Standard.prototype.q=function(s,a){return this.Q[s]&&this.Q[s][a]||0;};Standard.prototype.choose=function(s,A){var st=this.state(s);if(Math.random()<this.e)return A[Math.floor(Math.random()*A.length)];var b=A[0],v=-1e99;A.forEach(function(a){var x=this.q(st,a);if(x>v){v=x;b=a;}},this);return b;};Standard.prototype.learn=function(s,a,r,ns,A){var nx=0;A.forEach(function(x){nx=Math.max(nx,this.q(ns,x));},this);if(!this.Q[s])this.Q[s]={};var o=this.q(s,a);this.Q[s][a]=o+this.a*(r+this.g*nx-o);};
function MODQL(){this.Q1={};this.Q2={};this.a=.1;this.g=.9;this.e=.2;}MODQL.prototype.q=function(T,s,a){return T[s]&&T[s][a]||0;};MODQL.prototype.state=function(s){var pending=COMM.filter(function(n){return!s.served[n.id];}),mx=Math.max.apply(null,COMM.map(function(n){return n.demand;}));var pressure=pending.length?Math.max.apply(null,pending.map(function(n){return n.demand/mx;})):0,D=bucket(pressure,[.01,.45,.75]),T=bucket(s.remaining/MAX_STEPS,[.2,.4,.6,.8]),H=bucket(jain(COMM.map(function(n){return s.visits[n.id];})),[.55,.70,.85]),A=bucket(s.world.access(s.current),[.25,.5,.75]);return'L='+s.current+'|D='+D+'|T='+T+'|H='+H+'|A='+A;};MODQL.prototype.choose=function(s,A){var st=this.state(s);if(Math.random()<this.e)return A[Math.floor(Math.random()*A.length)];var b=A[0],v=-1e99;A.forEach(function(a){var x=this.q(this.Q1,st,a)+this.q(this.Q2,st,a);if(x>v){v=x;b=a;}},this);return b;};MODQL.prototype.learn=function(s,a,r,ns,A){var one=Math.random()<.5,X=one?this.Q1:this.Q2,Y=one?this.Q2:this.Q1,b=null,v=-1e99;A.forEach(function(x){var z=this.q(X,ns,x);if(z>v){v=z;b=x;}},this);var target=r+(b?this.g*this.q(Y,ns,b):0);if(!X[s])X[s]={};var o=this.q(X,s,a);X[s][a]=o+this.a*(target-o);};
function Sim(kind,w,agent){this.kind=kind;this.world=w;this.agent=agent;this.current='hub';this.remaining=MAX_STEPS;this.steps=0;this.reward=0;this.coverage=0;this.served={};this.visits={};this.routes=[];this.last='None';this.done=false;COMM.forEach(function(n){this.visits[n.id]=n.visits;},this);}Sim.prototype.actions=function(){var s=this;return COMM.filter(function(n){var p=s.world.route(s.current,n.id);return!s.served[n.id]&&p.length&&(p.length-1)<=s.remaining;}).map(function(n){return n.id;});};Sim.prototype.step=function(){var A=this.actions();if(!A.length){this.done=true;return;}var st=this.agent.state(this),a=this.agent.choose(this,A),path=this.world.route(this.current,a),cost=path.length-1,n=BY[a];this.remaining-=cost;this.steps+=cost;this.served[a]=1;this.visits[a]++;this.coverage+=n.demand;this.routes.push(path);this.last=a;var r=this.kind==='standard'?1/Math.max(cost,1):(n.demand/71)*jain(COMM.map(function(x){return this.visits[x.id];},this))*(1/Math.max(cost,1));this.reward+=r;this.current=a;var ns=this.agent.state(this),next=this.actions();this.agent.learn(st,a,r,ns,next);if(!next.length)this.done=true;};
var seed=20260905,ep=1,stdAgent=new Standard(),modAgent=new MODQL(),std,mod,timer=null;function reset(newSeed){if(newSeed)seed++;std=new Sim('standard',new World(seed),stdAgent);mod=new Sim('modql',new World(seed),modAgent);render();}function step(){if(!std.done)std.step();if(!mod.done)mod.step();render();if(std.done&&mod.done)stop();}function play(){if(timer){stop();return;}timer=setInterval(step,TICK);render();}function stop(){if(timer){clearInterval(timer);timer=null;}render();}function fresh(){stop();ep++;reset(true);}
function draw(cv,s,proposed){if(!cv)return;var x=cv.getContext('2d'),cell=40,ox=15,oy=15;x.clearRect(0,0,430,430);for(var r=0;r<SIZE;r++)for(var c=0;c<SIZE;c++){x.fillStyle=s.world.grid[r][c]?'#f2c94c':'#f8fafc';x.fillRect(ox+c*cell,oy+r*cell,cell,cell);x.strokeStyle='#d8dee8';x.strokeRect(ox+c*cell,oy+r*cell,cell,cell);}s.routes.forEach(function(p){x.beginPath();x.strokeStyle=proposed?'#2e67d1':'#d94747';x.lineWidth=3;p.forEach(function(z,i){var a=ox+z[1]*cell+20,b=oy+z[0]*cell+20;i?x.lineTo(a,b):x.moveTo(a,b);});x.stroke();});ALL.forEach(function(n){var a=ox+n.c*cell+20,b=oy+n.r*cell+20;x.beginPath();x.fillStyle=n.id==='hub'?'#2ca56d':s.served[n.id]?'#8fd9ba':'#34495e';x.arc(a,b,11,0,Math.PI*2);x.fill();x.fillStyle='#fff';x.font='bold 10px sans-serif';x.textAlign='center';x.fillText(n.id==='hub'?'H':n.id,a,b+3);});var n=BY[s.current];x.beginPath();x.fillStyle=proposed?'#1c4fa8':'#b52f2f';x.arc(ox+n.c*cell+20,oy+n.r*cell+20,6,0,Math.PI*2);x.fill();}
function panel(s,title,proposed){return'<div class="card"><h3>'+title+'</h3><div class="k">'+(proposed?'Q1 + Q2 &middot; S=&lang;L,D,T,H,A&rang; &middot; C &times; J &times; (1/Cost)':'Single Q-table &middot; S=L &middot; 1/Travel Cost')+'</div><canvas id="'+(proposed?'mazeMod':'mazeStd')+'" width="430" height="430" style="width:100%;max-width:430px;background:#fff;border-radius:10px;margin-top:8px"></canvas><div class="g3"><div class="kpi"><div class="lab">Coverage</div><div class="v">'+s.coverage+'</div></div><div class="kpi"><div class="lab">Jain J</div><div class="v">'+jain(COMM.map(function(n){return s.visits[n.id];})).toFixed(3)+'</div></div><div class="kpi"><div class="lab">Steps</div><div class="v">'+s.steps+'</div></div></div><div class="k">Last action: <b>'+s.last+'</b> &middot; cumulative reward: '+s.reward.toFixed(4)+'</div></div>';}
function render(){var root=document.getElementById('sub-maze');if(!root)return;root.innerHTML='<div class="algo-head mod"><div class="ic">&#8644;</div><div><h2>Maze Demo &mdash; Algorithm Comparison</h2><p>Same environment: Standard Q-Learning vs proposed MODQL</p></div></div><div class="card"><div class="k"><b>Defense note:</b> This is a controlled simulated micro-routing demo for algorithm mechanics, not final Chapter 4 evidence.</div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:10px"><button id="mazePlay">'+(timer?'Pause':'Play')+'</button><button id="mazeStep">Step</button><button id="mazeNew">New Episode</button><span class="tag">Episode '+ep+'</span><span class="tag">Same seed '+seed+'</span></div></div><div class="split2">'+panel(std,'Existing &mdash; Standard Q-Learning',false)+panel(mod,'Proposed &mdash; MODQL',true)+'</div><div class="card"><h3>What is being compared</h3><table><thead><tr><th>Component</th><th>Existing</th><th>Proposed</th></tr></thead><tbody><tr><td>Estimator</td><td>Single Q-table</td><td>Q1 + Q2, decoupled update</td></tr><tr><td>State</td><td>L only</td><td>L, D, T, H, A</td></tr><tr><td>Reward</td><td>Travel efficiency</td><td>Coverage &times; Jain fairness &times; 1/travel cost</td></tr><tr><td>Environment</td><td colspan="2">Identical 10&times;10 layout and community demand/history</td></tr></tbody></table></div>';document.getElementById('mazePlay').onclick=play;document.getElementById('mazeStep').onclick=step;document.getElementById('mazeNew').onclick=fresh;draw(document.getElementById('mazeStd'),std,false);draw(document.getElementById('mazeMod'),mod,true);}
function init(){if(document.getElementById('sub-maze'))reset(false);}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();